spring.application.name=food

# 로그 색상
spring.output.ansi.enabled=always
# 로그 설정
logging.level.root=info

## Oracle DB Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=food
spring.datasource.password=123456

#Oracle JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# create: 서버가 실행될 때 마다 새로테이블을 생성, update: 최초 없으면 생성, 이전 DB를 그대로 보관
spring.jpa.hibernate.ddl-auto=create

#로그 쿼리 출력
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# MyBatis Mapper XML 위치 지정
mybatis.mapper-locations=classpath:mapper/*.xml

# DTO 패키지 alias 설정
mybatis.type-aliases-package=com.pknu26.food.dto